### ISSUE TITLE
Delete sidebar post meta when updating from two-column to one-column posts in Largo update functions

### ISSUE THREAD

**Issue by benlk** [INN/Largo#1040]
For [VO-8](http://jira.inn.org/browse/VO-8) and [WE-43](http://jira.inn.org/browse/WE-43):

Because the default option for the sidebar is automatically selected in the post's editor metabox, saving the post commits that sidebar option to the database, even if it is the default. 

- [ ] metabox save should not save the sidebar option if the sidebar option that is POSTed with the form is the default sidebar option

Because all previous posts have a sidebar option set, changing the post template from two-column to one-column means that one-column posts appear with a set sidebar. Removing the set sidebar either requires editing the post meta per post, or dropping all rows in the `wp_postmeta` table where `meta_key` is equal to `custom_sidebar`. ([source for custom_sidebar assertion](https://github.com/INN/Largo/blob/f4ddf0b27b5fc34fb826e7ac22a9c393b4cbed1a/inc/sidebars.php#L135))

- [ ] optional update function to delete all previously-set custom sidebars
- [ ] create way to do optional updates in the update function

**Comment by aschweigert** [comment]
fwiw i fixed this on women's enews by just running a sql command to update the option for any post that had it set and it took like two seconds

**Comment by benlk** [comment]
What was the command?

**Comment by aschweigert** [comment]
@benlk some options: https://gist.github.com/aschweigert/c6fc7db56c2e777ff34a (replace the site ID, obviously)

**Comment by benlk** [comment]
@aschweigert What's your opinion on this one? Do we need a layout-changing function as part of the 0.3->0.recent update functions?

This issue feels like two separate issues:

- Don't save the sidebar if it's not set
- Optional update to remove all sidebars

**Comment by aschweigert** [comment]
Yeah, that seems fine to me. 

Note that the update script probably shouldn't remove ALL sidebars, just ones that are set to "default" or "single" because if a site had created custom sidebars associated with particular posts (or sets of posts) they'd probably want those to be preserved (and maybe even force those to use the two column layout because I REALLY want to lose the option to have a sidebar on the one column template entirely if we can)

**Comment by benlk** [comment]
Do we want to do this?

**Comment by benlk** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [do we want to reset sidebar choices when upgrading from two-column to one-column posts?](https://trello.com/c/JBmSmvqz/46-do-we-want-to-reset-sidebar-choices-when-upgrading-from-two-column-to-one-column-posts)
