### ISSUE TITLE
media credit plugin saves a bunch of nonsense as image meta

### ISSUE THREAD

**Issue by aschweigert** [INN/Largo#1412]
when you add an image (any image, featured media, etc. and save it, it stuffs the markup for the entire html table from the editor that contains the extra media fields (credit, url, org, etc.) in the postmeta table. 

for example:

{"success":true,"data":{"id":856,"title":"A-iUsnrCIAEHb2q","filename":"A-iUsnrCIAEHb2q.jpeg","url":"http:\/\/adamschweigert.com\/files\/2012\/12\/A-iUsnrCIAEHb2q.jpeg","link":"http:\/\/adamschweigert.com\/a-iusnrciaehb2q\/","alt":"","author":"1","description":"","caption":"","name":"a-iusnrciaehb2q","status":"inherit","uploadedTo":0,"date":1356019623000,"modified":1489684384000,"menuOrder":0,"mime":"image\/jpeg","type":"image","subtype":"jpeg","icon":"https:\/\/adamschweigert.com\/wp-includes\/images\/media\/default.png","dateFormatted":"December 20, 2012","nonces":{"update":"46500d0ed6","delete":"9927fd2691","edit":"eb1593eeb3"},"editLink":"https:\/\/adamschweigert.com\/wp-admin\/post.php?post=856&action=edit","meta":false,"authorName":"Adam Schweigert","filesizeInBytes":8467,"filesizeHumanReadable":"8 KB","height":240,"width":240,"orientation":"landscape","sizes":{"thumbnail":{"height":140,"width":140,"url":"http:\/\/adamschweigert.com\/files\/2012\/12\/A-iUsnrCIAEHb2q-140x140.jpeg","orientation":"landscape"},"full":{"url":"http:\/\/adamschweigert.com\/files\/2012\/12\/A-iUsnrCIAEHb2q.jpeg","height":240,"width":240,"orientation":"landscape"}},"compat":{"item":"<input type=\"hidden\" name=\"attachments[856][menu_order]\" value=\"0\" \/><p class=\"media-types media-types-required-info\">Required fields are marked <span class=\"required\">*<\/span><\/p>\n\t\t\t<table class=\"compat-attachment-fields\">\t\t<tr class='compat-field-media_credit'>\t\t\t<th scope='row' class='label'><label for='attachments-856-media_credit'><span class='alignleft'>Credit<\/span><br class='clear' \/><\/label><\/th>\n\t\t\t<td class='field'><input type='text' class='text' id='attachments-856-media_credit' name='attachments[856][media_credit]' value='asdfa'  \/><\/td>\n\t\t<\/tr>\n\t\t<tr class='compat-field-media_credit_url'>\t\t\t<th scope='row' class='label'><label for='attachments-856-media_credit_url'><span class='alignleft'>Credit URL<\/span><br class='clear' \/><\/label><\/th>\n\t\t\t<td class='field'><input type='text' class='text' id='attachments-856-media_credit_url' name='attachments[856][media_credit_url]' value='asdf'  \/><\/td>\n\t\t<\/tr>\n\t\t<tr class='compat-field-navis_media_credit_org'>\t\t\t<th scope='row' class='label'><label for='attachments-856-navis_media_credit_org'><span class='alignleft'>Organization<\/span><br class='clear' \/><\/label><\/th>\n\t\t\t<td class='field'><input type='text' class='text' id='attachments-856-navis_media_credit_org' name='attachments[856][navis_media_credit_org]' value='asdfasdf'  \/><\/td>\n\t\t<\/tr>\n\t\t<tr class='compat-field-navis_media_can_distribute'>\t\t\t<th scope='row' class='label'><label for='attachments-856-navis_media_can_distribute'><span class='alignleft'>Can<br \/>distribute?<\/span><br class='clear' \/><\/label><\/th>\n\t\t\t<td class='field'><input id=\"attachments[856][navis_media_can_distribute]\" name=\"attachments[856][navis_media_can_distribute]\" type=\"checkbox\" value=\"1\"  \/><\/td>\n\t\t<\/tr>\n<\/table>","meta":""}}}

**Comment by rclations** [comment]
will need an upgrade script to fix all the legacy data we've stored on sites in this manner

**Comment by benlk** [comment]
Edited adam's comment to make the formatting of the JSON clearer. The "data" property is generated by [wp_prepare_attachment_for_js](https://codex.wordpress.org/Function_Reference/wp_prepare_attachment_for_js), which stuffs that table into the "compat" field.

We use that function a couple of times, only in `inc/featured-media.php`: https://github.com/INN/Largo/search?utf8=%E2%9C%93&q=wp_prepare_attachment_for_js

I don't know if we use the data from "compat" anywhere, though.

**Comment by benlk** [comment]
- [ ] check if we use `compat`
- [ ] remove the addition of this metadata
- [ ] see what breaks in Largo, in the Classic Editor and otherwise.

**Comment by benlk** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [stop saving junk in image meta](https://trello.com/c/JWPjzFIG/64-stop-saving-junk-in-image-meta)
