### ISSUE TITLE
Migrate Theme Options => Customizer

### ISSUE THREAD

**Issue by rclations** [INN/largo#1438]

**Comment by benlk** [comment]
Past research on this topic:

- https://github.com/INN/largo/issues/1417#issuecomment-293341761
- https://github.com/INN/largo/issues/1423#issuecomment-295802166

This will encompass:

- [ ] research how the Customizer prefers to deal with data
- [ ] losslessly morph the existing optionsframework metadata to theme mods format as part of Largo's upgrade function
- [ ] test for that upgrade
- [ ] provide shim function for `of_get_option` and `of_set_option` if possible for child themes to prevent immediately-upon-upgrade breakage
- [ ] recreate the Theme Options settings in the Customizer, possibly using "selective refresh" as described in https://github.com/INN/largo/issues/1438
- [ ] replace Largo's custom site icon logic with WordPress' in https://github.com/INN/largo/issues/835
- [ ] check if https://github.com/INN/largo/issues/243 is still an issue
- [ ] (low priority) fix https://github.com/INN/largo/issues/1823

**Comment by MirandaEcho** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Options framework --> customizer](https://trello.com/c/dqHu5Mdi/4-options-framework-customizer)
