### ISSUE TITLE
Add Gutenberg compatibility for Largo's custom meta boxes and editor functionality

### ISSUE THREAD

**Issue by benlk** [INN/largo#1491]
https://github.com/danielbachhuber/gutenberg-migration-guide

- [ ] find all the custom things we do
- [ ] create tickets for migrating/shimming each thing

**Comment by benlk** [comment]
https://wptavern.com/block-unit-test-plugin-helps-wordpress-theme-developers-prepare-for-gutenberg describes https://wordpress.org/plugins/block-unit-test/

**Comment by benlk** [comment]
For meta boxes that aren't immediately compatible with Gutenberg (read: everything using Largo's meta box API), we can add a flag to show they aren't compatible: https://wordpress.org/gutenberg/handbook/extensibility/meta-box/#testing-converting-and-maintaining-existing-meta-boxes

**Comment by benlk** [comment]
Add to release notes or docs for Gutenberg: For sites that are using the Custom Fields meta box frequently, they'll need to install https://wordpress.org/plugins/custom-fields-gutenberg/ to get it in WordPress.

**Comment by benlk** [comment]
https://make.wordpress.org/core/2018/11/07/meta-box-compatibility-flags/

**Comment by benlk** [comment]
https://github.com/danielbachhuber/gutenberg-migration-guide

**Comment by benlk** [comment]
Is there anything here that still needs to be done?

**Comment by benlk** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Do we need to do anything more to Largo's metaboxes for Gutenberg support?](https://trello.com/c/WgIJ3fXC/56-do-we-need-to-do-anything-more-to-largos-metaboxes-for-gutenberg-support)

**Comment by benlk** [comment]
- [ ] top term selector needs to reflect terms available in REST API for post at current time, not terms set on post at page load

**Comment by benlk** [comment]
Closing in favor of #1795 and specific issues in the future.
