### ISSUE TITLE
0.6.2 pre-release to-do checklist

### ISSUE THREAD

**Issue by benlk** [INN/Largo#1690]
This is copied from https://github.com/INN/largo/issues/809, which is the reference issue for the pre-release checklist.

The owner of the release needs to complete the following steps BEFORE merging to master and tagging the release:

- [x] run the [theme check plugin](https://wordpress.org/plugins/theme-check/) and address any outstanding issues
- [x] using [WP sample data](https://wpcom-themes.svn.automattic.com/demo/theme-unit-test-data.xml), go through the entire [theme unit tests checklist]
- [x] design checklist tktk (add to the list of theme unit tests, including style guidance, patterns that need to be followed, etc., eventually this will be codified in the INN/Largo style guide)
	- [x] click around: don't just visually check the homepage, but also internal pages: https://github.com/INN/docs/blob/master/checklists/child-themes.md
	- [x] Homepage `/`
		- [x] Blog
		- [x] Big Story, full-width image
		- [x] Big story, list of featured stories
		- [x] Big Story, list of stories from same series
		- [x] Top Stories
		- [x] Legacy Three Column
	- [x] Articles `/?p=1234`
	- [x] Series `/series/slug/` `/?series=1234`
	- [x] Category archive pages `/category/slug/`
	- [x] Series archive pages `/series/slug/`
	- [x] Series landing pages `/slug/`
	- [x] Search results `/?s=words`
	- [x] Pages `/slug/`
	- [x] Tag archives `/tag/slug`
	- [x] Load More Posts
	- [x] Sticky nav
		- [x] Mobile
		- [x] Desktop
	- [x] Non-sticky nav
	- [x] Widgets
		- [x] Default background
		- [x] Reverse Background
		- [x] No Background
	- [x] Article
		- [x] Social buttons
		- [x] Type
		- [x] Fonts rendered are fonts specified in stylesheet ( In Chrome: "Inspect element" on a `<p>`, then look at the bottom of the "Computed" tab. )
		- [x] Images
	- [x] Footer
- [x] check that the LESS Customizer works
- [x] move any outstanding issues to future milestones or backlog
- [x] resolve all secret issues, private issues, or issues with the theme that are otherwise documented outside of this public repository
- [x] update the changelog
	- [x] New features list
	- [x] bugfixes
	- [x] potentially breaking changes and upgrade notices
- [x] run `grunt build`
- [ ] release announcement blog post written and saved as draft
- [x] update all version numbers
- [x] merge 0.5-dev into 0.5
- [x] tag release `git tag -s v0.6.2`
- [x] create release at https://github.com/INN/largo/releases
- [x] close milestone

After release is tagged:

- [ ] recompile LESS on all child themes, and see https://github.com/INN/docs/blob/master/checklists/child-themes.md
- [ ] new release needs to be deployed to our sites - largo-umbrella, inndev, other standalone instances (wisconsin, etc.)
- [ ] notify non-INN sites
- [ ] publish launch announcement blog post
- [ ] update version number on largo.inn.org, like in INN/umbrella-inndev#36
- [ ] tweet announcement and schedule 2-5 for the next 7 days (TweetDeck, HootSuite) with simple download prompt or "Newsroom Staff Pages should be clean and useful. We think so too. See Largo 0.X's new....". Make sure they get cross-tweet'd between INN accounts.

**Comment by benlk** [comment]
Closing in favor of https://github.com/INN/largo/issues/1694
