### ISSUE TITLE
Largo 0.6.4 release checklist

### ISSUE THREAD

**Issue by benlk** [INN/Largo#1704]
This is copied from https://github.com/INN/largo/issues/809, which is the reference issue for the pre-release checklist.

The owner of the release needs to complete the following steps **BEFORE** merging to master and tagging the release:

- [x] run the [theme check plugin](https://wordpress.org/plugins/theme-check/) and address any outstanding issues. 
- [ ] using [WP sample data](https://wpcom-themes.svn.automattic.com/demo/theme-unit-test-data.xml), go through the entire [theme unit tests checklist](https://codex.wordpress.org/Theme_Unit_Test)
- [x] Update the INN Sandbox repo submodules https://github.com/INN/umbrella-innsandbox/tree/master/wp-content/themes and take a look around the sandbox sites, making sure to test all testable items. — https://github.com/INN/umbrella-innsandbox/commit/a868c0ced3c30e7d0313a118d8941ea53d408c6a
- [ ] design checklist tktk (add to the list of theme unit tests, including style guidance, patterns that need to be followed, etc., eventually this will be codified in the INN/Largo style guide)
	- [ ] click around: don't just visually check the homepage, but also internal pages: https://github.com/INN/docs/blob/master/checklists/child-themes.md
	- [x] Homepage `/`
		- [x] Blog
		- [x] Big Story, full-width image
		- [x] Big story, list of featured stories
		- [x] Big Story, list of stories from same series
		- [x] Top Stories
		- [x] Legacy Three Column
	- [x] Articles `/?p=1234`
	- [x] Series `/series/slug/` `/?series=1234`
	- [x] Category archive pages `/category/slug/`
	- [x] Series archive pages `/series/slug/`
	- [x] Series landing pages `/slug/`
	- [x] Search results `/?s=words`
	- [x] Pages `/slug/`
	- [x] Tag archives `/tag/slug`
	- [x] Load More Posts
	- [x] Sticky nav
		- [x] Mobile
		- [x] Desktop
	- [x] Non-sticky nav
	- [ ] Widgets
		- [ ] Default background
		- [ ] Reverse Background
		- [ ] No Background
	- [x] Article
		- [x] Social buttons
		- [x] Type
		- [x] Fonts rendered are fonts specified in stylesheet ( In Chrome: "Inspect element" on a `<p>`, then look at the bottom of the "Computed" tab. )
		- [x] Image display
		- [x] slideshows, see https://github.com/INN/largo/issues/1664
	- [x] Footer
- [x] check that the LESS Customizer works
- [x] test the plugins described in `docs/developers/plugin-compat.rst`
- [x] move any outstanding issues to future milestones or backlog
- [x] resolve all secret issues, private issues, or issues with the theme that are otherwise documented outside of this public repository
- [x] update the changelog
	- [x] New features list
	- [x] bugfixes
	- [x] potentially breaking changes and upgrade notices
- [ ] release announcement
    - [ ] labs.inn.org blog post written and saved as draft
    - [x] GitHub release drafted
        - [ ] includes encouragement to say hi if you're using the theme. (This fulfills the "who's using our stuff?" goal in https://github.com/INN/largo/issues/1495)
        - [ ] includes links to upgrade info from #1713 
- [x] update all version numbers. `0.6.4-prerelease.x` all become `0.6.4`. 
- [x] run `grunt build`
- [x] merge 0.5-dev into 0.5

Releasing:

- [x] tag release `git tag -s v0.6.4`
- [x] create release at https://github.com/INN/largo/releases
- [x] close milestone

After release is tagged:

- [x] update version number on largo.inn.org, like in INN/umbrella-inndev#36
- [x] bump version number in active-development branch to `0.7.0-prerelease`, as described in https://github.com/INN/largo/pull/1705
- [x] rename branches as described in https://github.com/INN/largo/issues/1571
https://github.com/INN/largo/pull/1705
- [x] notify non-INN sites
- [ ] recompile LESS on all child themes, and see https://github.com/INN/docs/blob/master/checklists/child-themes.md
- [x] new release needs to be deployed to our sites
    - inndev
    - innsandbox
    - inndevlearn
- [x] compare this ticket to the template used to create this ticket, and update the template
- [ ] create the 0.6.5 release ticket from the template used to create this issue
- [x] publish launch announcement blog post
- [x] tweet announcement and schedule 2-5 for the next 7 days (TweetDeck, HootSuite) with simple download prompt or tweets detailing new features, like "Newsroom Staff Pages should be clean and useful. We think so too. See Largo 0.X's new...." Make sure these tweets get cross-tweeted between INN accounts.

**Comment by benlk** [comment]
We will also need to update the helpdesk docs for the changes introduced in #1733.

**Comment by benlk** [comment]
- [x] can we get the "you aren't reading the latest version" prompt on https://largo.readthedocs.io/ to go away?

**Comment by benlk** [comment]
Today's combined list:

- [x] can we get the "you aren't reading the latest version" prompt on https://largo.readthedocs.io/ to go away? — @benlk 
- [x] release announcement — @kaylima 
    - [x] labs.inn.org blog post written and saved as draft
    - [x] GitHub release drafted
        - [x] includes encouragement to say hi if you're using the theme. (This fulfills the "who's using our stuff?" goal in https://github.com/INN/largo/issues/1495) — @benlk 
        - [x] includes links to upgrade info from #1713 — @benlk 
- [x] rename branches as described in https://github.com/INN/largo/issues/1571 @joshdarby 
https://github.com/INN/largo/pull/1705
- [ ] notify non-INN sites
- [ ] recompile LESS on all child themes, and see https://github.com/INN/docs/blob/master/checklists/child-themes.md
- [x] new release needs to be deployed to our sites @joshdarby 
    - inndev
    - innsandbox
    - inndevlearn
- [x] compare this ticket to the template used to create this ticket, and update the template — @benlk
- [x] create the 0.7.0 release ticket from the template used to create this issue — @benlk 
- [x] publish launch announcement blog post
- [x] tweet announcement and schedule 2-5 for the next 7 days (TweetDeck, HootSuite) with simple download prompt or tweets detailing new features, like "Newsroom Staff Pages should be clean and useful. We think so too. See Largo 0.X's new...." Make sure these tweets get cross-tweeted between INN accounts.
